### PR TITLE
Fix for Http Dektop DiagnosticSource instrumentation

### LINKED ISSUE #480: Breaking DiagnosticSource changes for Http on NET 4.6
Heads up on DiagnosticSource [change](https://github.com/dotnet/corefx/commit/28b6bbff681b956fbe1e0a5e2133e99dc280b17b?diff=split) in PR [18502](https://github.com/dotnet/corefx/pull/18502).

This change affects reflection hook that instruments WebRequests on .NET46 with DiganosticSource.
It changes events names and starts Activity/injects headers itself.

The rationale for this change: events sent with this hook should be consistent with HttpClient instrumentation on .NET Core. If we don't do it right now, before it became public, we would have to deal with deprecation hell later and we know it's going to be painful for everyone: event producer and consumers (including AI).

What needs to be fixed in AI **2.4.0** Web SDK:
- event names
- AI should not start Activity for dependency if the hook was called.

### PR DESCRIPTION
**Pull request by lmolkova**
Fixes #480

### CODE REVIEW

File: Src/DependencyCollector/Shared/Implementation/HttpDiagnosticSourceListener.cs [hunk 1]
```diff
@@ -47,14 +47,16 @@ public void OnNext(KeyValuePair<string, object> value)
             {
                 switch (value.Key)
                 {
-                    case "System.Net.Http.Request":
+                    case "System.Net.Http.Desktop.HttpRequestOut.Start": 
+                    case "System.Net.Http.Request": // remove in 2.5.0
```
Comment (SergeyKanzhelev) [inline Src/DependencyCollector/Shared/Implementation/HttpDiagnosticSourceListener.cs]: please expand the comment with the link to the issue or just write in words why it should be removed.

File: Src/DependencyCollector/Shared/Implementation/ClientServerDependencyTracker.cs [hunk 2]
```diff
@@ -28,40 +28,51 @@ internal static DependencyTelemetry BeginTracking(TelemetryClient telemetryClien
...
+                {
+                    activity.SetParentId(telemetry.Id);
+                }
 
-            //// end of workaround
+                //// end of workaround
 
-            activity.Start();
-            
+                activity.Start();
```
Comment (SergeyKanzhelev) [inline Src/DependencyCollector/Shared/Implementation/ClientServerDependencyTracker.cs]: why do we need to start and stop it?

Comment (lmolkova) [inline Src/DependencyCollector/Shared/Implementation/ClientServerDependencyTracker.cs]: In case dependency was tracked with profiler, we need to generate new hierarchical Id for it. We use Activity to generate it.

We can also manually append AI-generated DependencyTelemetry.Id to the Activity.Current.Id (if any).
So the code would look a bit more simple.

``` 
            if (currentActivity != null && currentActivity.OperationName == "System.Net.Http.Desktop.HttpRequestOut")
            {
                telemetry.Id = currentActivity.Id;
            }            
            else 
            {
                var parentId = currentActivity?.Id ?? '|';
                telemetry.Id = parentId  + telemetry.Id + '.';
            }

            if (string.IsNullOrEmpty(telemetry.Context.Operation.Id))
            {
                telemetry.Context.Operation.Id = currentActivity?.RootId ??  telemetry.Id 
            }
```
 I'm fine with doing it this way

Comment (lmolkova) [inline Src/DependencyCollector/Shared/Implementation/ClientServerDependencyTracker.cs]: After careful consideration I think it's  a bad idea to manually generate Id even if simplifies code: it would make Id grow too fast (Activity will append 1 digit, while telemetry.Id is much longer)
Also, if for some reason Id generation changes in Activity, it may cause grief in AI

Comment (SergeyKanzhelev) [inline Src/DependencyCollector/Shared/Implementation/ClientServerDependencyTracker.cs]: just put an extensive comment there why you are doing it.

Comment (SergeyKanzhelev) [inline Src/DependencyCollector/Shared/Implementation/ClientServerDependencyTracker.cs]: Do you think profiler need to use Activity instead of "manual" tracking?

Comment (lmolkova) [inline Src/DependencyCollector/Shared/Implementation/ClientServerDependencyTracker.cs]: Yes, it need to inject proper Id into Http header

**Comment by lmolkova** [comment]
I provided more detailed comments, please have a lokk and merge if there are no other objections
